version: "3.7"

services:
  grpc-server-go:
    build:
      context: ../
      dockerfile: ./Dockerfile  
      target: builder
    volumes:
      - ../:/go/src/workdir
      # synchronize with parent's proto
      - ../../proto:/go/src/workdir/proto
    env_file:
      - ../.env
    stdin_open: true
    tty: true
    
networks: 
  default: 
    external: 
      name: grpc-go