version: "3.8"

services:
  grpc-client-python:
    build:
      context: ../
      dockerfile: ./Dockerfile  
    volumes:
      - ../:/root/workdir
      # synchronize with parent's proto
      - ../../proto:/root/workdir/proto
    env_file:
      - ../.env
    stdin_open: true
    tty: true

networks: 
  default: 
    external: 
      name: grpc-go
